# Generated by Django 5.0.4 on 2024-05-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
